i18n
grrr-amsterdam/nova-publish pull request #14
Opened 2023-04-21 13:15 UTC by martijngastkemper

2023-06-15 07:31 UTC, HammenWS requested changes
Excuses. Ik heb deze gemist en zag 'm ook niet op komen in het #tech-prs kanaal.

LGTM. Maar kan niet zomaar gemerged worden. `main` is nu een Nova 4 package.

2023-06-15 07:31 UTC, HammenWS commented on README.md
> +Use the local checkout in a projecdt that uses this plugin. [The Composer documentation explains how to do this.](https://getcomposer.org/doc/05-repositories.md#path)
```suggestion
Use the local checkout in a project that uses this plugin. [The Composer documentation explains how to do this.](https://getcomposer.org/doc/05-repositories.md#path)
```

2024-03-08 09:18 UTC, martijngastkemper commented
@HammenWS Ik heb deze PR compatible gemaakt met `main`, zodat die op Nova 4 werk. Lokaal met Schoolwijzer getest.

2024-12-02 12:36 UTC, harmenjanssen commented
Closing this because it is superseded by https://github.com/grrr-amsterdam/nova-publish/pull/19.

2024-12-02 12:36 UTC, closed without merging